version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password 
      MYSQL_DATABASE: team_dev_db
      MYSQL_USER: team_user
      MYSQL_PASSWORD: user_password
    # ports:
    #   - "127.0.0.1:3306:3306" #ポートフォアディングをローカルホスト内に指定。
    expose:
      - "3306"

    volumes:
      - db_data:/var/lib/mysql 
    restart: always #コンテナが停止したら自動的に再起動

  api:
    build: 
      context: ./app
      dockerfile: dockerfile.yaml
    container_name: api
    volumes: 
      - ./app:/app
      - ./html:/app/statics
    # ports:
    #   - "127.0.0.1:3000:3000" #ポートフォアディングをローカルホストに指定。
    expose:
      - "3000"
    depends_on:
      - db 

  nginx:
    image: nginx:1-alpine
    container_name: nginx
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro  # 証明書ファイルをマウント
      - ./html:/usr/share/nginx/html
    depends_on:
      - api
    restart: always #コンテナが停止した場合に自動的の再起動


volumes:
  db_data: