version: '3.8'


services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password 
      MYSQL_DATABASE: team_dev_db
      MYSQL_USER: team_user
      MYSQL_PASSWORD: user_password
    ports:
      - "127.0.0.1:3306:3306" #ポートフォアディングをローカルホスト内に指定。
    volumes:
      - db_data:/var/lib/mysql 
    restart: always #コンテナが停止したら自動的に再起動

  nginx:
    image: nginx:1-alpine
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf #ローカルのディレクトリをnginxのドキュメントルートにマウント
    depends_on:
      - api
    restart: always #コンテナが停止した場合に自動的の再起動


  api:
    build: ./app
    command: ruby app_main.rb 
    volumes: 
      - ./app:/app
    ports:
      - "127.0.0.1:3000:3000" #ポートフォアディングをローカルホストに指定。
    depends_on:
      - db 
  
volumes:
  db_data:
